# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  branches:
    include:
    - refs/tags/v*
    - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'dDPSm.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CmdLine@2
  inputs:
    script: 'git clone https://github.com/mmosalon/dDPSm-data.git'
- task: DeleteFiles@1
  inputs:
    SourceFolder: 
    Contents: 'dDPSm-data/.git'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'dDPSm/bin/Release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'dDPSm-data'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/nDPSm.zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'nDPSm'
    publishLocation: 'Container'